services:
  issues-tracker-backend:
    container_name: issues-tracker-backend
    image: issues-tracker-backend:latest
    build: 
      context: ./backend-api
    ports:
    - "8091:8091"
    networks:
      - issues-tracker-network
      - postgres-network
      - nginx-network
    restart: always

  issues-tracker-frontend:
    container_name: issues-tracker-frontend
    image: issues-tracker-frontend:latest
    build:
      context: ./vue
    ports:
      - "8092:8080"
    networks:
      - issues-tracker-network
      - nginx-network
    restart: always

networks:
  issues-tracker-network:
    name: issues-tracker-network
    driver: bridge

  postgres-network:
    name: postgres-network
    external: true

  nginx-network:
    name: nginx-network
    external: true

  
